Added the new bot.js file and the response.js files
zolwethu/profile-with-nova pull request #1
Opened 2024-10-24 12:30 UTC by zolwethu

Added a new file

2024-11-01 07:58 UTC, TshepoMagagula commented on Nova/control/chatbot-services.js
>                  botMessage = "What would you like to know about Sibusiso? Please choose ";
This message keeps popping up but there is no options to choose from

2024-11-01 07:59 UTC, TshepoMagagula commented on Nova/control/chatbot-services.js
>              if (userInput.toLowerCase().includes("hello")) {
Try to make the chat bot control the conversation, instead of saying "type anything"

2024-11-06 13:24 UTC, BAHLEMAJOLA commented
![image](https://github.com/user-attachments/assets/5bf39123-b8fd-4e7b-991e-32aa185f4378)
@zolwethu Please fix the spacing between the chatbot's welcome text and the user's message.

2024-11-06 13:26 UTC, BAHLEMAJOLA requested changes
![image](https://github.com/user-attachments/assets/5bf39123-b8fd-4e7b-991e-32aa185f4378)
@zolwethu Please fix the spacing between the chatbot's welcome text and the user's message.

2024-11-12 05:56 UTC, closed without merging

2024-11-12 05:56 UTC, TshepoMagagula commented
> ![image](https://private-user-images.githubusercontent.com/50671955/383569086-5bf39123-b8fd-4e7b-991e-32aa185f4378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTEyMjMsIm5iZiI6MTczMTM5MDkyMywicGF0aCI6Ii81MDY3MTk1NS8zODM1NjkwODYtNWJmMzkxMjMtYjhmZC00ZTdiLTk5MWUtMzJhYTE4NWY0Mzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA1NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZDZjYTkxNjZkZmRiNmM5NDYxZjQ5ZTI4NjZhNGFlYjI3ZjAxYzZiMjE2MGJiMzhmOGQ0YTQ1NTNhMWRiNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nV606bTG7pXpigM7gWLxC1SC5dV0kdhDz3YuyEi4WVY) @zolwethu Please fix the spacing between the chatbot's welcome text and the user's message.